# Generated by Django 5.0.1 on 2024-04-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
                ('icon', models.CharField(max_length=50, verbose_name='icon name')),
            ],
        ),
    ]
