# Generated by Django 5.0.1 on 2024-04-18 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_name_alter_events_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubServers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image10', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image11', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image12', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image13', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image14', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image15', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image16', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image17', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image18', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image19', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image20', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image21', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image22', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image23', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image24', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image25', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image26', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image27', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image28', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image29', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image30', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image31', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image32', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image33', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image34', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image35', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image36', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image37', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image38', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image39', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('image40', models.ImageField(blank=True, null=True, upload_to='SubServers')),
                ('Service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
        ),
    ]
